name: Publish

on:
  workflow_run:
    workflows: Test
    branches: master
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 17

      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - run: yarn install

      - name: Publish 📄
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
